name: Deploy Vite site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # ✅ Checkout latest commit (full history, handles fast pushes)
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      # ✅ Set up Node.js
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # ✅ Install dependencies inside the client folder
      - name: Install dependencies
        run: |
          cd client
          npm install

      # ✅ Build the Vite site
      - name: Build site
        run: |
          cd client
          npm run build

      # ✅ Deploy the dist folder to the gh-pages branch
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./client/dist
